version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: aliyun-balance-bot
    restart: unless-stopped
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - PORT=5000
      - ADMIN_CHAT_IDS=${ADMIN_CHAT_IDS}
      - CHECK_INTERVAL=${CHECK_INTERVAL:-300}
      - ENABLE_MONITORING=${ENABLE_MONITORING:-true}
      - DATABASE_PATH=/app/data/bot_data.db
      - ALIYUN_ACCESS_KEY_ID=${ALIYUN_ACCESS_KEY_ID}
      - ALIYUN_ACCESS_KEY_SECRET=${ALIYUN_ACCESS_KEY_SECRET}
      - ALIYUN_RESELLER_TEST_UID=${ALIYUN_RESELLER_TEST_UID}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - bot-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  bot-network:
    driver: bridge

volumes:
  bot-data:
  bot-logs:
